### ISSUE TITLE
removeLabel(String labelToRemove) is not working

### ISSUE THREAD

**Issue by porksteak** [DavidPizarro/AutoLabelUI#3]
the findViewWithTag(labelToRemove) always return null

**Comment by DavidPizarro** [comment]
Hi!
Could you send me a little example, a snippet or more information? I'm testing that and I can't reproduce it. Tell me the phone model and Android version please.

**Comment by porksteak** [comment]
When I use addLabel(String label, int position) to add a label, I can't use removeLabel(String label) to remove this label. and I can't add label to a specific position.
So, I change addLabel(String label, int position) to allow add label to a specific position and fix removeLabel issue in "fix-issue3" branch.

Thank you and your library, I use it in my app and it works perfect!
...and sorry about my poor English :stuck_out_tongue:

**Comment by DavidPizarro** [comment]
Great!
I've seen the new branch that you have created and have accepted the pull request . Thank you for helping! Remember that methods 'addLabel(String textLabel, int position)'  and 'removeLabel(int position)' must be used ONLY with Lists (RecyclerView for example).
Soon I will update the Maven version to be updated by Gradle.

Is your application published in Google Play? Because I have decided to put in the Readme, the applications which using the library. So also they have more visibility.

If you want, you can pass me the link and add it!!
